/* Daily Immersive Read — client app.
   Data comes from reads.json (regenerated by build_reader.py).
   All user state lives in localStorage until an account backend is wired up. */

(function () {
  'use strict';

  var KEY = 'dir.v1';
  var TOPIC_COLOR = {
    'ai technology': '#8c491a',
    'geopolitics': '#d67f48',
    'environment': '#728157',
    'environment/climate': '#728157',
    'economics': '#645c50'
  };
  var SIZES = [15, 16, 17, 19, 21];
  var SIZE_LABELS = ['Small', 'Cosy', 'Default', 'Large', 'Largest'];
  var NAV = [
    ['today', 'Today'], ['progress', 'Progress'], ['archive', 'Archive'],
    ['marks', 'Bookmarks'], ['settings', 'Settings'], ['account', 'Account']
  ];
  var SUGGESTED = ['Semiconductors', 'ASEAN trade', 'Coral reefs', 'Central banks', 'Space policy'];

  var ICON = {
    menu: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
    check: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg>',
    bookmark: '<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>',
    back: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>',
    sun: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
    moon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/></svg>',
    user: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 3.6-6 8-6s8 2 8 6"/></svg>'
  };

  // ── state ────────────────────────────────────────────────
  var defaults = { read: {}, marks: {}, theme: 'auto', size: 2, topics: {}, queue: [], remind: true };
  var S = load();
  var DATA = { days: [], generated: '' };

  function load() {
    try {
      var raw = JSON.parse(localStorage.getItem(KEY) || '{}');
      var out = {};
      for (var k in defaults) out[k] = (k in raw) ? raw[k] : defaults[k];
      return out;
    } catch (e) { return JSON.parse(JSON.stringify(defaults)); }
  }
  function save() { try { localStorage.setItem(KEY, JSON.stringify(S)); } catch (e) {} }

  // ── helpers ──────────────────────────────────────────────
  function el(id) { return document.getElementById(id); }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); }
  function color(topic) { return TOPIC_COLOR[String(topic).toLowerCase()] || '#645c50'; }
  function allEntries() {
    var out = [];
    DATA.days.forEach(function (d) { d.entries.forEach(function (e) { out.push({ day: d, entry: e }); }); });
    return out;
  }
  function findEntry(id) {
    var hit = allEntries().filter(function (x) { return x.entry.id === id; })[0];
    return hit || null;
  }
  function activeDay() {
    // Newest day that still has an unread entry; otherwise the newest day.
    for (var i = 0; i < DATA.days.length; i++) {
      var d = DATA.days[i];
      if (d.entries.some(function (e) { return !S.read[e.id]; })) return d;
    }
    return DATA.days[0] || null;
  }
  function teaser(e) {
    var txt = String(e.bodyHtml || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
    if (txt.length <= 150) return txt;
    var cut = txt.slice(0, 150);
    var stop = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf('\u2014'));
    var out = stop > 70 ? cut.slice(0, stop + 1) : cut.replace(/\s\S*$/, '') + '\u2026';
    return out.replace(/[\s\u2014\u2013,;:-]+(\u2026)?$/, function (m) { return m.indexOf('\u2026') > -1 ? '\u2026' : '\u2026'; });
  }
  function readDayCount() {
    return DATA.days.filter(function (d) {
      return d.entries.some(function (e) { return S.read[e.id]; });
    }).length;
  }
  function nextBonus(exclude) {
    var pool = allEntries().filter(function (x) {
      return !S.read[x.entry.id] && (!exclude || x.day.date !== exclude.date);
    });
    return pool.length ? pool[0] : null;
  }

  // ── theme ────────────────────────────────────────────────
  var mq = window.matchMedia('(prefers-color-scheme: dark)');
  function isDark() { return S.theme === 'dark' || (S.theme === 'auto' && mq.matches); }
  function applyTheme() {
    document.documentElement.setAttribute('data-theme', isDark() ? 'dark' : 'light');
    document.documentElement.style.setProperty('--ui-size', SIZES[S.size] + 'px');
    var meta = document.querySelector('meta[name="theme-color"]');
    if (meta) meta.setAttribute('content', isDark() ? '#1a1714' : '#f5ead8');
    el('themeBtn').innerHTML = isDark() ? ICON.sun : ICON.moon;
    var sw = el('drawerTheme');
    if (sw) sw.setAttribute('aria-checked', isDark() ? 'true' : 'false');
  }
  if (mq.addEventListener) mq.addEventListener('change', function () { if (S.theme === 'auto') { applyTheme(); render(); } });

  // ── routing ──────────────────────────────────────────────
  function route() {
    var h = (location.hash || '#/today').replace(/^#\//, '').split('/');
    return { name: h[0] || 'today', arg: h[1] ? decodeURIComponent(h[1]) : null };
  }
  function go(path) { location.hash = '#/' + path; }
  window.addEventListener('hashchange', function () { render(); window.scrollTo(0, 0); });

  // ── screens ──────────────────────────────────────────────
  function screenToday() {
    var day = activeDay();
    if (!day) return '<div class="empty">No reads yet. Run the generator on your laptop and refresh.</div>';

    var total = day.entries.length;
    var done = day.entries.filter(function (e) { return S.read[e.id]; }).length;
    var left = day.entries.filter(function (e) { return !S.read[e.id]; });
    var minsLeft = left.reduce(function (a, e) { return a + (e.mins || 2); }, 0);
    var next = left[0] || null;
    var readDays = readDayCount();

    var WORD = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five'];
    var head = done === 0
      ? WORD[total] + ' reads, then you\u2019re done.'
      : WORD[done] + ' down, ' + WORD[total - done].toLowerCase() + ' to go.';

    // label is "Saturday, 15 August 2026" - split so the date can be styled
    // separately. The year is dropped here; the archive still shows it in full.
    var labelParts = day.label.split(', ');
    var dayName = labelParts[0];
    var dayDate = (labelParts[1] || '').replace(/\s+\d{4}$/, '');

    var html = '<div class="dayhead"><span class="dayname">' + esc(dayName) + '</span>' +
      (dayDate ? '<span class="daydate">' + esc(dayDate) + '</span>' : '') +
      '<button class="daypill" data-go="progress">' + readDays + ' days read</button></div>' +
      '<h2 class="daylede">' + (done === total ? 'That\u2019s the day closed.' : head) + '</h2>' +
      '<p class="daysub">' + (done === total
        ? esc(day.label)
        : 'About ' + minsLeft + ' minute' + (minsLeft === 1 ? '' : 's') + ' left in today\u2019s read') + '</p>';

    if (day.date !== DATA.days[0].date) {
      html += '<p class="daynote">Nothing new since ' + esc(DATA.days[0].label) +
        ' \u2014 this is the newest day you haven\u2019t finished.</p>';
    }

    html += '<ol class="path">' + day.entries.map(function (e) {
      var read = !!S.read[e.id];
      var isNext = next && e.id === next.id;
      var state = read ? 'done' : isNext ? 'next' : 'todo';
      var marked = !!S.marks[e.id];

      var node = '<button class="node ' + state + '" data-read="' + esc(e.id) + '" aria-label="' +
        (read ? 'Mark unread' : 'Mark read') + '">' + (read ? ICON.check : '') + '</button>';

      var kicker = '<span class="stepkicker">' + esc(e.topic) +
        (isNext ? ' <i>\u00b7 up next</i>' : '') + '</span>';

      if (isNext) {
        return '<li class="step next">' + node +
          '<div class="stepbody"><div class="nextcard">' +
            '<div class="nextmeta">' + kicker +
              '<span class="mins">' + e.mins + ' min</span>' +
              '<button class="markbtn' + (marked ? ' on' : '') + '" data-mark="' + esc(e.id) +
              '" aria-label="Bookmark" style="fill:' + (marked ? 'currentColor' : 'none') + '">' + ICON.bookmark + '</button>' +
            '</div>' +
            '<h3 class="nexttitle">' + esc(e.title) + '</h3>' +
            '<p class="nextteaser">' + esc(teaser(e)) + '</p>' +
            '<button class="btn-solid nextbtn" data-open="' + esc(e.id) + '">Read this one</button>' +
          '</div></div></li>';
      }

      return '<li class="step ' + state + '">' + node +
        '<button class="stepbody steplink" data-open="' + esc(e.id) + '">' + kicker +
        '<span class="steptitle">' + esc(e.title) + '</span></button></li>';
    }).join('') + '</ol>';

    if (done === total && total > 0) {
      var bonus = nextBonus(day);
      html += '<div class="dayclosed"><h2>That\u2019s today, done.</h2>' +
        '<p>' + total + ' reads. Come back tomorrow \u2014 or take one extra if you\u2019re still curious.</p>' +
        (bonus ? '<button class="btn-solid nextbtn" data-open="' + esc(bonus.entry.id) + '">One bonus read</button>'
               : '<p style="margin:0">Nothing unread left in the archive. Genuinely done.</p>') +
        '</div>';
      html += '<div class="panel" style="margin-top:14px"><h3>Want something specific tomorrow?</h3>' +
        '<div class="chips">' + SUGGESTED.map(function (t) {
          return '<button data-chip="' + esc(t) + '"' + (S.queue.indexOf(t) > -1 ? ' class="on"' : '') + '>' + esc(t) + '</button>';
        }).join('') + '</div>' +
        '<div class="queuerow"><input class="input" id="queueInput" placeholder="or type a topic\u2026"><button id="queueBtn">Queue</button></div>' +
        (S.queue.length ? '<p style="margin:12px 0 0;font-size:.74rem;color:var(--color-neutral-700)">Queued: ' + esc(S.queue.join(', ')) + '</p>' : '') +
        '</div>';
    } else {
      html += '<p class="pathfoot">Finish the path and the day closes. Nothing loads after the ' +
        (total === 4 ? 'fourth' : 'last') + '.</p>';
    }
    return html;
  }

  function screenReader(id) {
    var hit = findEntry(id);
    if (!hit) return '<div class="empty">That read is no longer in the log.</div>';
    var e = hit.entry, marked = !!S.marks[e.id], read = !!S.read[e.id];
    var siblings = hit.day.entries;
    var i = siblings.indexOf(e);
    var next = siblings[i + 1];

    return '<article class="article">' +
      '<div class="artmeta">' +
        '<span class="artkicker">' + esc(e.topic) + ' \u00b7 read ' + (i + 1) + ' of ' + siblings.length + '</span>' +
        '<span class="mins">' + e.mins + ' min</span>' +
      '</div>' +
      '<h1>' + esc(e.title) + '</h1>' +
      '<div class="artrule"></div>' +
      (e.bodyHtml || '') +
      (e.whyHtml ? '<div class="why"><b>Why it matters</b><p>' + e.whyHtml + '</p></div>' : '') +
      (e.noteHtml ? '<div class="note">' + e.noteHtml + '</div>' : '') +
      (e.sourceHtml ? '<p class="source">' + e.sourceHtml + '</p>' : '') +
      '<div class="readeractions">' +
        '<button class="btn-outline" data-read="' + esc(e.id) + '">' + (read ? 'Read' : 'Mark as read') + '</button>' +
        '<button class="btn-outline btn-mark' + (marked ? ' on' : '') + '" data-mark="' + esc(e.id) +
        '" style="flex:none;width:52px;fill:' + (marked ? 'currentColor' : 'none') + '" aria-label="Bookmark">' + ICON.bookmark + '</button>' +
        (next ? '<button class="btn-solid" data-open="' + esc(next.id) + '">Next: ' + esc(next.topic) + '</button>'
              : '<button class="btn-solid" data-go="today">Back to today</button>') +
      '</div>' +
    '</article>';
  }

  function screenProgress() {
    var days = [], today = new Date();
    for (var i = 34; i >= 0; i--) {
      var d = new Date(today.getTime() - i * 86400000);
      var key = d.toISOString().slice(0, 10);
      var rec = DATA.days.filter(function (x) { return x.date === key; })[0];
      var on = !!(rec && rec.entries.some(function (e) { return S.read[e.id]; }));
      days.push({ key: key, on: on });
    }
    var readDays = days.filter(function (d) { return d.on; }).length;
    var entries = Object.keys(S.read).filter(function (k) { return S.read[k]; }).length;
    var mins = allEntries().filter(function (x) { return S.read[x.entry.id]; })
      .reduce(function (a, x) { return a + (x.entry.mins || 2); }, 0);

    return '<p style="margin:0 0 18px;font-size:.86rem;line-height:1.5;color:var(--color-neutral-700)">' +
      'No streak to break. Squares fill as you read; blank days are just blank.</p>' +
      '<div class="panel"><div class="gridhead"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div>' +
      '<div class="grid">' + days.map(function (d) {
        return '<div class="' + (d.on ? 'on' : '') + '" title="' + d.key + '"></div>';
      }).join('') + '</div>' +
      '<div class="stats">' +
        '<div><b>' + readDays + '</b><span>days read</span></div>' +
        '<div><b>' + entries + '</b><span>entries</span></div>' +
        '<div><b>' + Math.floor(mins / 60) + 'h ' + (mins % 60) + 'm</b><span>reading</span></div>' +
      '</div></div>' +
      '<div class="panel" style="background:var(--color-accent-100)"><p style="margin:0;font-size:.86rem;line-height:1.55;color:var(--color-accent-900)">' +
      'Days with nothing new — the laptop was off — aren\'t misses, so they don\'t count against you.</p></div>';
  }

  function screenArchive() {
    if (!DATA.days.length) return '<div class="empty">Nothing in the archive yet.</div>';
    return '<div class="rowlist">' + DATA.days.map(function (d) {
      var done = d.entries.filter(function (e) { return S.read[e.id]; }).length;
      var state = done === d.entries.length ? 'All read' : done ? done + ' of ' + d.entries.length : 'Unread';
      var col = done === d.entries.length ? 'var(--color-accent-2-700)' : done ? 'var(--color-accent-700)' : 'var(--color-neutral-600)';
      return '<button class="row" data-day="' + esc(d.date) + '">' +
        '<span style="flex:1;min-width:0"><b>' + esc(d.label) + '</b><small>' +
        esc(d.entries.map(function (e) { return e.title; }).join(' · ')) + '</small></span>' +
        '<span class="rowstate" style="color:' + col + '">' + state + '</span></button>';
    }).join('') + '</div>';
  }

  function screenMarks() {
    var saved = allEntries().filter(function (x) { return S.marks[x.entry.id]; });
    if (!saved.length) return '<div class="empty">Nothing saved yet. Tap the ribbon on any read to keep it here.</div>';
    return '<div class="rowlist">' + saved.map(function (x) {
      return '<button class="row" data-open="' + esc(x.entry.id) + '">' +
        '<span class="dot" style="background:' + color(x.entry.topic) + '"></span>' +
        '<span style="flex:1;min-width:0"><b>' + esc(x.entry.title) + '</b><small>' +
        esc(x.entry.topic) + ' · ' + esc(x.day.label) + '</small></span></button>';
    }).join('') + '</div>';
  }

  function screenSettings() {
    var topics = {};
    allEntries().forEach(function (x) { topics[x.entry.topic] = true; });
    var names = Object.keys(topics);

    return '<div class="panel"><h3>Appearance</h3>' +
      '<div class="seg3">' + ['light', 'dark', 'auto'].map(function (t) {
        return '<button data-theme="' + t + '"' + (S.theme === t ? ' class="on"' : '') + '>' +
          t.charAt(0).toUpperCase() + t.slice(1) + '</button>';
      }).join('') + '</div>' +
      '<div class="settingrow" style="margin-bottom:6px"><span style="font-weight:600;font-size:.88rem">Text size</span>' +
      '<span style="font-size:.8rem;color:var(--color-neutral-700)">' + SIZE_LABELS[S.size] + '</span></div>' +
      '<div class="sizerow"><span style="font-size:.7rem">A</span>' +
      '<input type="range" min="0" max="4" step="1" value="' + S.size + '" id="sizeRange">' +
      '<span style="font-size:1.15rem">A</span></div></div>' +

      '<div class="panel"><h3>Topics you follow</h3>' + names.map(function (n) {
        var on = S.topics[n] !== false;
        return '<button class="topicrow" data-topic="' + esc(n) + '">' +
          '<span class="dot" style="background:' + color(n) + '"></span>' +
          '<span class="name">' + esc(n) + '</span>' +
          '<span class="switch" aria-checked="' + on + '"><span></span></span></button>';
      }).join('') + '</div>' +

      '<div class="panel"><h3>Reminders</h3>' +
      '<div class="settingrow"><div><div style="font-size:.88rem">Nudge me at</div>' +
      '<small>Only if today\'s reads aren\'t finished</small></div>' +
      '<input class="input" type="time" id="remindTime" value="' + (S.remindAt || '19:30') + '" style="width:auto"></div>' +
      '<div class="settingrow"><div><div style="font-size:.88rem">New reads ready</div>' +
      '<small>Fires when the laptop wakes and publishes</small></div>' +
      '<button class="switch" id="remindSwitch" role="switch" aria-checked="' + !!S.remind + '"><span></span></button></div></div>' +

      '<div class="panel"><h3>Install</h3>' +
      '<p style="margin:0 0 12px;font-size:.86rem;line-height:1.5;color:var(--color-neutral-700)">' +
      'On iPhone: Share &rarr; Add to Home Screen. On Android: menu &rarr; Install app. It then opens full-screen and works offline.</p></div>' +

      '<div class="panel"><h3>Your data</h3>' +
      '<p style="margin:0 0 12px;font-size:.86rem;line-height:1.5;color:var(--color-neutral-700)">' +
      'Reading history and bookmarks live on this device. Export a copy to move them to another one.</p>' +
      '<div style="display:flex;gap:8px"><button class="btn-outline" id="exportBtn" style="border-radius:999px;padding:10px 18px;font-weight:600;font-size:.76rem;cursor:pointer;font-family:var(--font-body)">Export</button>' +
      '<button class="btn-outline" id="importBtn" style="border-radius:999px;padding:10px 18px;font-weight:600;font-size:.76rem;cursor:pointer;font-family:var(--font-body)">Import</button></div></div>';
  }

  function screenAccount() {
    return '<div class="account"><div class="avatar">' + ICON.user + '</div>' +
      '<h2>Keep your reads on every device</h2>' +
      '<p>Sign in and your bookmarks, settings and which days you\'ve read follow you between phone and laptop. No password to forget, none for us to lose.</p>' +
      '<div class="authbtns">' +
        '<button class="auth-google" data-auth="google"><span style="font-weight:700;color:#4285F4">G</span>Continue with Google</button>' +
        '<button class="auth-apple" data-auth="apple"><span style="font-size:1rem"></span>Continue with Apple</button>' +
      '</div>' +
      '<p class="fineprint">Sign-in needs a free Firebase project to be connected — see <code>README.md</code>. Until then the buttons explain what is missing, and Export/Import in Settings moves your data by hand. Reading works fully signed out; sync is the only thing you lose.</p></div>';
  }

  // ── render ───────────────────────────────────────────────
  var TITLES = { today: "Today's four", reader: '', progress: 'Progress', archive: 'Archive', marks: 'Bookmarks', settings: 'Settings', account: 'Account' };

  function render() {
    var r = route();
    var body;
    if (r.name === 'read') { body = screenReader(r.arg); el('barTitle').textContent = ''; }
    else if (r.name === 'progress') { body = screenProgress(); el('barTitle').textContent = 'Days you read'; }
    else if (r.name === 'archive') { body = screenArchive(); el('barTitle').textContent = TITLES.archive; }
    else if (r.name === 'marks') { body = screenMarks(); el('barTitle').textContent = TITLES.marks; }
    else if (r.name === 'settings') { body = screenSettings(); el('barTitle').textContent = TITLES.settings; }
    else if (r.name === 'account') { body = screenAccount(); el('barTitle').textContent = TITLES.account; }
    else { body = screenToday(); el('barTitle').textContent = TITLES.today; }
    el('screen').innerHTML = body;
    document.body.setAttribute('data-screen', r.name === 'read' ? 'read' : r.name);
    var mb = el('menuBtn');
    mb.dataset.mode = r.name === 'read' ? 'back' : 'menu';
    mb.innerHTML = r.name === 'read' ? ICON.back : ICON.menu;
    mb.setAttribute('aria-label', r.name === 'read' ? 'Back to today' : 'Menu');

    el('drawerNav').innerHTML = NAV.map(function (n) {
      var on = n[0] === r.name || (r.name === 'read' && n[0] === 'today');
      return '<button data-go="' + n[0] + '"' + (on ? ' class="on"' : '') + '>' + n[1] + '</button>';
    }).join('');
    applyTheme();
  }

  // ── events ───────────────────────────────────────────────
  document.addEventListener('click', function (ev) {
    var t = ev.target.closest('[data-open],[data-read],[data-mark],[data-go],[data-theme],[data-topic],[data-chip],[data-day],[data-auth]');
    if (!t) return;

    if (t.dataset.open) {
      S.read[t.dataset.open] = true; save();
      closeDrawer(); go('read/' + encodeURIComponent(t.dataset.open));
      return;
    }
    if (t.dataset.read) { S.read[t.dataset.read] = !S.read[t.dataset.read]; save(); render(); return; }
    if (t.dataset.mark) { S.marks[t.dataset.mark] = !S.marks[t.dataset.mark]; save(); render(); return; }
    if (t.dataset.go) { closeDrawer(); go(t.dataset.go); return; }
    if (t.dataset.theme) { S.theme = t.dataset.theme; save(); applyTheme(); render(); return; }
    if (t.dataset.topic) {
      var n = t.dataset.topic;
      S.topics[n] = S.topics[n] === false; save(); render(); return;
    }
    if (t.dataset.chip) {
      var c = t.dataset.chip, i = S.queue.indexOf(c);
      if (i > -1) S.queue.splice(i, 1); else S.queue.push(c);
      save(); render(); return;
    }
    if (t.dataset.day) {
      var d = DATA.days.filter(function (x) { return x.date === t.dataset.day; })[0];
      if (d && d.entries[0]) go('read/' + encodeURIComponent(d.entries[0].id));
      return;
    }
    if (t.dataset.auth) {
      alert('Sign-in is not connected yet.\n\nAdd a free Firebase project (Auth + Firestore) and fill in the config in README.md. Until then, use Export / Import in Settings to move your reading history between devices.');
      return;
    }
  });

  document.addEventListener('input', function (ev) {
    if (ev.target.id === 'sizeRange') { S.size = +ev.target.value; save(); applyTheme(); render(); }
    if (ev.target.id === 'remindTime') { S.remindAt = ev.target.value; save(); }
  });

  document.addEventListener('click', function (ev) {
    if (ev.target.closest('#remindSwitch')) { S.remind = !S.remind; save(); render(); }
    if (ev.target.closest('#queueBtn')) {
      var inp = el('queueInput');
      if (inp && inp.value.trim()) { S.queue.push(inp.value.trim()); save(); render(); }
    }
    if (ev.target.closest('#exportBtn')) {
      var blob = new Blob([JSON.stringify(S, null, 2)], { type: 'application/json' });
      var a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = 'daily-read-backup.json';
      a.click();
    }
    if (ev.target.closest('#importBtn')) {
      var f = document.createElement('input');
      f.type = 'file'; f.accept = 'application/json';
      f.onchange = function () {
        var fr = new FileReader();
        fr.onload = function () {
          try { S = Object.assign({}, defaults, JSON.parse(fr.result)); save(); applyTheme(); render(); }
          catch (e) { alert('That file could not be read.'); }
        };
        fr.readAsText(f.files[0]);
      };
      f.click();
    }
  });

  function openDrawer() { el('drawer').hidden = false; }
  function closeDrawer() { el('drawer').hidden = true; }
  el('menuBtn').addEventListener('click', function () {
    if (el('menuBtn').dataset.mode === 'back') go('today'); else openDrawer();
  });
  el('scrim').addEventListener('click', closeDrawer);
  el('themeBtn').addEventListener('click', function () {
    S.theme = isDark() ? 'light' : 'dark'; save(); applyTheme(); render();
  });
  el('drawerTheme').addEventListener('click', function () {
    S.theme = isDark() ? 'light' : 'dark'; save(); applyTheme(); render();
  });

  // ── boot ─────────────────────────────────────────────────
  applyTheme();
  fetch('./reads.json', { cache: 'no-cache' })
    .then(function (r) {
      // A 404 still resolves, so check explicitly - otherwise the real cause
      // surfaces later as a confusing JSON parse error.
      if (!r.ok) { throw new Error('HTTP ' + r.status + ' fetching reads.json'); }
      return r.json();
    })
    .then(function (json) { DATA = json; render(); })
    .catch(function (err) {
      var isFile = location.protocol === 'file:';
      var offline = !navigator.onLine;
      var msg =
        isFile ? 'Open this over http://localhost, not as a file:// path - the browser blocks reads.json on file://.' :
        offline ? 'You\'re offline. The last synced copy will appear once you reconnect.' :
        'Couldn\'t load today\'s reads.';
      el('screen').innerHTML = '<div class="empty">' + msg + '</div>';
      console.error('reads.json failed to load:', err);
    });
})();
